// File generated by flutterfire_cli
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQoX3T5k69HvUYekS-CTnbjzyRQvqkXA',
    appId: '1:542729551050:web:c9b0a73e12c8dfb0d80833',
    messagingSenderId: '542729551050',
    projectId: 'appstudydeck-e036d',
    authDomain: 'appstudydeck-e036d.firebaseapp.com',
    storageBucket: 'appstudydeck-e036d.firebasestorage.app',
    measurementId: 'G-JV2TXWBGQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNgYJwze5_t_AwXTLNuNALDBDEaWqo3Y',
    appId: '1:542729551050:android:45d4d81cafc47bafd80833',
    messagingSenderId: '542729551050',
    projectId: 'appstudydeck-e036d',
    storageBucket: 'appstudydeck-e036d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_onwkvdDEXtRTP33FLI2vETrBtZLO0A',
    appId: '1:542729551050:ios:125a7ad81dab7aebd80833',
    messagingSenderId: '542729551050',
    projectId: 'appstudydeck-e036d',
    storageBucket: 'appstudydeck-e036d.firebasestorage.app',
    iosBundleId: 'com.example.flashcardStudydeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_onwkvdDEXtRTP33FLI2vETrBtZLO0A',
    appId: '1:542729551050:ios:125a7ad81dab7aebd80833',
    messagingSenderId: '542729551050',
    projectId: 'appstudydeck-e036d',
    storageBucket: 'appstudydeck-e036d.firebasestorage.app',
    iosBundleId: 'com.example.flashcardStudydeck',
  );
}
